# Setup
title:               Modularizing My Mind
tagline:             Un nouveau blog pour une nouvelle vie
url:                 https://glefur.github.io/ 	
paginate:            1
baseurl:             "/modularizing-my-mind"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Goulwen Le Fur
  url:               https://twitter.com/glefur_
  email:             goulwen.lefur@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

twitter_username: glefur_
github_username:  glefur

